-- StyleAtHome UPDATED Seed — uses local images from /images/ folder
-- First clear old products so we don't duplicate
DELETE FROM products;
DELETE FROM categories;
-- Keep stores

-- UPDATED CATEGORIES (matching real image folders)
INSERT INTO categories (name, section) VALUES ('T-Shirts', 'Men');
INSERT INTO categories (name, section) VALUES ('Shirts', 'Men');
INSERT INTO categories (name, section) VALUES ('Jeans', 'Men');
INSERT INTO categories (name, section) VALUES ('Kurtas', 'Men');
INSERT INTO categories (name, section) VALUES ('Jackets', 'Men');
INSERT INTO categories (name, section) VALUES ('Ethnic Wear', 'Men');
INSERT INTO categories (name, section) VALUES ('Dresses', 'Women');
INSERT INTO categories (name, section) VALUES ('Tops', 'Women');
INSERT INTO categories (name, section) VALUES ('Kurtis', 'Women');
INSERT INTO categories (name, section) VALUES ('Sarees', 'Women');
INSERT INTO categories (name, section) VALUES ('Boys', 'Kids');
INSERT INTO categories (name, section) VALUES ('Girls', 'Kids');

-- PRODUCTS — MEN > T-Shirts (10 images available)
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Virat Noir Oversized Tee', 'Wrogn', 799, 1299, 'Premium heavyweight cotton oversized t-shirt with raw-edge detailing.', '/images/menswear/tshirts/tshirts1.jpg', (SELECT id FROM categories WHERE name='T-Shirts' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='wrogn' LIMIT 1), 'Men', 'Black', 'S, M, L, XL, XXL', 4.5, 312, true, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Urban Grid Polo', 'Wrogn', 1199, 1799, 'Structured polo with geometric grid pattern. Moisture-wicking fabric.', '/images/menswear/tshirts/tshirts2.jpg', (SELECT id FROM categories WHERE name='T-Shirts' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='wrogn' LIMIT 1), 'Men', 'Navy', 'S, M, L, XL', 4.3, 189, false, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Acid Wash Crew Neck', 'Zudio', 699, 999, 'Vintage acid wash finish on 100% organic cotton.', '/images/menswear/tshirts/tshirts3.jpg', (SELECT id FROM categories WHERE name='T-Shirts' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='zudio' LIMIT 1), 'Men', 'Grey', 'M, L, XL', 4.1, 87, false, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Minimal Stripe Essential', 'Zudio', 399, 599, 'Lightweight striped tee in breathable cotton blend.', '/images/menswear/tshirts/tshirts4.jpg', (SELECT id FROM categories WHERE name='T-Shirts' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='zudio' LIMIT 1), 'Men', 'White', 'S, M, L, XL', 4.0, 456, true, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Slim Fit Henley', 'Trends', 599, 899, 'Waffle-knit henley with rolled sleeves and wooden buttons.', '/images/menswear/tshirts/tshirts5.jpg', (SELECT id FROM categories WHERE name='T-Shirts' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='trends' LIMIT 1), 'Men', 'Red', 'S, M, L, XL', 4.2, 234, false, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Classic Round Neck Tee', 'Max Fashion', 499, 799, 'Essential round-neck in premium cotton jersey. Every wardrobe needs one.', '/images/menswear/tshirts/tshirts6.jpg', (SELECT id FROM categories WHERE name='T-Shirts' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='max-fashion' LIMIT 1), 'Men', 'Blue', 'S, M, L, XL', 4.4, 520, false, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Raglan Sleeve Sport Tee', 'Pantaloons', 649, 999, 'Athletic raglan tee with contrast sleeves. Dry-fit technology.', '/images/menswear/tshirts/tshirts7.jpg', (SELECT id FROM categories WHERE name='T-Shirts' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='pantaloons' LIMIT 1), 'Men', 'Grey', 'M, L, XL, XXL', 4.0, 145, true, true);

-- MEN > Shirts (10 images)
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Oxford Button-Down Classic', 'Westside', 1499, 2199, 'Premium Oxford cotton button-down with mother-of-pearl buttons.', '/images/menswear/shirts/shirts1.jpg', (SELECT id FROM categories WHERE name='Shirts' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='westside' LIMIT 1), 'Men', 'White', 'S, M, L, XL, XXL', 4.7, 234, false, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Denim Trucker Shirt', 'Wrogn', 1799, 2499, 'Heavy-duty indigo denim shirt with copper rivets.', '/images/menswear/shirts/shirts2.jpg', (SELECT id FROM categories WHERE name='Shirts' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='wrogn' LIMIT 1), 'Men', 'Blue', 'M, L, XL', 4.4, 156, true, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Linen Resort Shirt', 'Pantaloons', 1299, 1999, 'Pure linen camp-collar shirt with coconut shell buttons.', '/images/menswear/shirts/shirts3.jpg', (SELECT id FROM categories WHERE name='Shirts' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='pantaloons' LIMIT 1), 'Men', 'Beige', 'S, M, L, XL', 4.6, 98, false, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Mandarin Collar Shirt', 'Max Fashion', 899, 1399, 'Fusion mandarin collar shirt in cotton-linen blend.', '/images/menswear/shirts/shirts4.jpg', (SELECT id FROM categories WHERE name='Shirts' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='max-fashion' LIMIT 1), 'Men', 'Green', 'S, M, L, XL', 4.2, 67, false, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Flannel Check Shirt', 'Trends', 1099, 1599, 'Brushed flannel with classic tartan check. Warm and cozy.', '/images/menswear/shirts/shirts5.jpg', (SELECT id FROM categories WHERE name='Shirts' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='trends' LIMIT 1), 'Men', 'Red', 'S, M, L, XL', 4.3, 211, true, true);

-- MEN > Jeans (10 images)
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Raw Selvedge Slim Jean', 'Wrogn', 2499, 3499, 'Japanese 14oz raw selvedge denim. Slim tapered fit.', '/images/menswear/jeans/jeans1.jpg', (SELECT id FROM categories WHERE name='Jeans' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='wrogn' LIMIT 1), 'Men', 'Navy', '28, 30, 32, 34, 36', 4.8, 423, true, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Stretch Skinny Fit', 'Zudio', 999, 1499, 'Ultra-stretch denim with recovery fabric technology.', '/images/menswear/jeans/jeans2.jpg', (SELECT id FROM categories WHERE name='Jeans' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='zudio' LIMIT 1), 'Men', 'Black', '28, 30, 32, 34', 4.1, 287, false, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Cargo Relaxed Fit Jean', 'Trends', 1599, 2299, 'Relaxed cargo jeans with reinforced utility pockets.', '/images/menswear/jeans/jeans3.jpg', (SELECT id FROM categories WHERE name='Jeans' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='trends' LIMIT 1), 'Men', 'Grey', '30, 32, 34, 36', 4.3, 134, false, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Bootcut Classic Jean', 'Pantaloons', 1799, 2499, 'Vintage bootcut with washed finish and whisker detailing.', '/images/menswear/jeans/jeans4.jpg', (SELECT id FROM categories WHERE name='Jeans' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='pantaloons' LIMIT 1), 'Men', 'Blue', '30, 32, 34, 36', 4.5, 178, true, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Distressed Straight Fit', 'Westside', 1899, 2699, 'Artfully distressed straight-leg denim. Each pair unique.', '/images/menswear/jeans/jeans5.jpg', (SELECT id FROM categories WHERE name='Jeans' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='westside' LIMIT 1), 'Men', 'Blue', '28, 30, 32, 34', 4.4, 198, false, true);

-- MEN > Kurtas (10 images)
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Cotton Pathani Kurta', 'Pantaloons', 1299, 1999, 'Classic Pathani style kurta in pure cotton. Festive essential.', '/images/menswear/kurtas/kurtas1.jpg', (SELECT id FROM categories WHERE name='Kurtas' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='pantaloons' LIMIT 1), 'Men', 'White', 'S, M, L, XL, XXL', 4.6, 234, true, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Silk Blend Wedding Kurta', 'Westside', 2499, 3499, 'Premium silk blend with tone-on-tone embroidery. Wedding-ready.', '/images/menswear/kurtas/kurtas2.jpg', (SELECT id FROM categories WHERE name='Kurtas' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='westside' LIMIT 1), 'Men', 'Gold', 'S, M, L, XL', 4.8, 89, false, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Linen Short Kurta', 'Max Fashion', 899, 1399, 'Relaxed linen short kurta. Perfect for casual festive occasions.', '/images/menswear/kurtas/kurtas3.jpg', (SELECT id FROM categories WHERE name='Kurtas' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='max-fashion' LIMIT 1), 'Men', 'Blue', 'M, L, XL', 4.3, 167, true, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Printed Nehru Collar Kurta', 'Trends', 999, 1599, 'Geometric print kurta with Nehru collar. Modern ethnic fusion.', '/images/menswear/kurtas/kurtas4.jpg', (SELECT id FROM categories WHERE name='Kurtas' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='trends' LIMIT 1), 'Men', 'Navy', 'S, M, L, XL', 4.1, 112, false, true);

-- MEN > Jackets (10 images)
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Bomber Jacket Heritage', 'Wrogn', 2999, 4299, 'Quilted bomber with ribbed cuffs and satin lining.', '/images/menswear/jackets/jackets1.jpg', (SELECT id FROM categories WHERE name='Jackets' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='wrogn' LIMIT 1), 'Men', 'Black', 'S, M, L, XL', 4.7, 89, true, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Denim Trucker Jacket', 'Zudio', 1999, 2999, 'Classic trucker silhouette in washed indigo denim.', '/images/menswear/jackets/jackets2.jpg', (SELECT id FROM categories WHERE name='Jackets' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='zudio' LIMIT 1), 'Men', 'Blue', 'S, M, L, XL', 4.4, 234, false, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Puffer Jacket Winter', 'Pantaloons', 3499, 4999, 'Lightweight puffer with 700-fill down. Packable warmth.', '/images/menswear/jackets/jackets3.jpg', (SELECT id FROM categories WHERE name='Jackets' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='pantaloons' LIMIT 1), 'Men', 'Navy', 'M, L, XL, XXL', 4.6, 156, true, true);

-- MEN > Ethnic Wear (10 images)
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Sherwani Grand Set', 'Pantaloons', 5999, 8999, 'Royal sherwani with churidar. Embroidered yoke with sequin work.', '/images/menswear/ethnicwear/ethnicwear1.jpg', (SELECT id FROM categories WHERE name='Ethnic Wear' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='pantaloons' LIMIT 1), 'Men', 'Gold', 'S, M, L, XL', 4.9, 45, true, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Nehru Jacket Brocade', 'Westside', 2499, 3499, 'Brocade Nehru jacket with mandarin collar. Layer over kurta.', '/images/menswear/ethnicwear/ethnicwear2.jpg', (SELECT id FROM categories WHERE name='Ethnic Wear' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='westside' LIMIT 1), 'Men', 'Navy', 'S, M, L, XL', 4.5, 123, false, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Dhoti Kurta Set', 'Max Fashion', 1799, 2799, 'Contemporary dhoti pants with matching kurta. Festive ready.', '/images/menswear/ethnicwear/ethnicwear3.jpg', (SELECT id FROM categories WHERE name='Ethnic Wear' AND section='Men' LIMIT 1), (SELECT id FROM stores WHERE slug='max-fashion' LIMIT 1), 'Men', 'White', 'M, L, XL', 4.3, 87, true, true);

-- WOMEN > Dresses
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Floral Midi Wrap Dress', 'Westside', 2299, 3299, 'Georgette wrap dress with hand-painted floral motif.', '/images/womenswear/dresses/dresses1.jpg', (SELECT id FROM categories WHERE name='Dresses' AND section='Women' LIMIT 1), (SELECT id FROM stores WHERE slug='westside' LIMIT 1), 'Women', 'Red', 'XS, S, M, L', 4.7, 267, true, true);

-- WOMEN > Tops
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Cropped Puff Sleeve Top', 'Trends', 899, 1399, 'Statement puff sleeves on cropped silhouette.', '/images/womenswear/tops/tops1.jpg', (SELECT id FROM categories WHERE name='Tops' AND section='Women' LIMIT 1), (SELECT id FROM stores WHERE slug='trends' LIMIT 1), 'Women', 'Pink', 'XS, S, M, L', 4.3, 234, true, true);

-- WOMEN > Kurtis (5 images)
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Chanderi Silk Kurti', 'Pantaloons', 3499, 4999, 'Handwoven chanderi silk kurti with zari border.', '/images/womenswear/kurtis/kurtis1.jpg', (SELECT id FROM categories WHERE name='Kurtis' AND section='Women' LIMIT 1), (SELECT id FROM stores WHERE slug='pantaloons' LIMIT 1), 'Women', 'Blue', 'S, M, L, XL', 4.9, 89, true, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Cotton A-Line Printed Kurti', 'Max Fashion', 799, 1299, 'Lightweight cotton A-line kurti with block print motifs.', '/images/womenswear/kurtis/kurtis3.jpg', (SELECT id FROM categories WHERE name='Kurtis' AND section='Women' LIMIT 1), (SELECT id FROM stores WHERE slug='max-fashion' LIMIT 1), 'Women', 'Yellow', 'S, M, L, XL, XXL', 4.3, 412, false, true);

-- WOMEN > Sarees (4 images)
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Banarasi Silk Saree', 'Pantaloons', 4999, 7999, 'Handloom Banarasi silk with intricate zari weaving. Heirloom quality.', '/images/sarees/saree1.jpeg', (SELECT id FROM categories WHERE name='Sarees' AND section='Women' LIMIT 1), (SELECT id FROM stores WHERE slug='pantaloons' LIMIT 1), 'Women', 'Red', 'Free Size', 4.9, 156, true, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Chiffon Party Saree', 'Westside', 2999, 4499, 'Lightweight chiffon saree with sequin border. Party-perfect drape.', '/images/sarees/saree2.jpeg', (SELECT id FROM categories WHERE name='Sarees' AND section='Women' LIMIT 1), (SELECT id FROM stores WHERE slug='westside' LIMIT 1), 'Women', 'Blue', 'Free Size', 4.6, 98, false, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Cotton Handloom Saree', 'Max Fashion', 1299, 1999, 'Everyday cotton handloom with traditional motifs. Breathable elegance.', '/images/sarees/saree3.jpeg', (SELECT id FROM categories WHERE name='Sarees' AND section='Women' LIMIT 1), (SELECT id FROM stores WHERE slug='max-fashion' LIMIT 1), 'Women', 'Green', 'Free Size', 4.4, 234, true, true);
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Organza Embroidered Saree', 'Trends', 3499, 5499, 'Sheer organza with thread embroidery and mirror work. Showstopper.', '/images/sarees/saree4.jpeg', (SELECT id FROM categories WHERE name='Sarees' AND section='Women' LIMIT 1), (SELECT id FROM stores WHERE slug='trends' LIMIT 1), 'Women', 'Pink', 'Free Size', 4.7, 67, false, true);

-- KIDS > Boys
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Dino Adventure Tee Set', 'Max Fashion', 699, 999, 'Colorful dinosaur graphic tee with matching shorts. Bio-washed cotton.', '/images/kidswear/boys/boys1.jpg', (SELECT id FROM categories WHERE name='Boys' AND section='Kids' LIMIT 1), (SELECT id FROM stores WHERE slug='max-fashion' LIMIT 1), 'Kids', 'Green', '2-3Y, 4-5Y, 6-7Y, 8-9Y', 4.6, 234, true, true);

-- KIDS > Girls
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Tutu Party Dress', 'Pantaloons', 1299, 1899, 'Layered tulle tutu dress with sequin bodice.', '/images/kidswear/girls/girls1.jpg', (SELECT id FROM categories WHERE name='Girls' AND section='Kids' LIMIT 1), (SELECT id FROM stores WHERE slug='pantaloons' LIMIT 1), 'Kids', 'Pink', '2-3Y, 4-5Y, 6-7Y, 8-9Y', 4.8, 145, true, true);

-- KIDS > Infants
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Soft Cotton Romper', 'Max Fashion', 499, 799, 'Ultra-soft organic cotton romper with snap buttons. Gentle on baby skin.', '/images/kidswear/infants/infants1.jpg', (SELECT id FROM categories WHERE name='Boys' AND section='Kids' LIMIT 1), (SELECT id FROM stores WHERE slug='max-fashion' LIMIT 1), 'Kids', 'White', '0-3M, 3-6M, 6-12M', 4.7, 312, true, true);

-- KIDS > Winter Wear
INSERT INTO products (name, brand, price, mrp, description, image_url, category_id, store_id, section, color, sizes, rating, review_count, is_new_arrival, is_active) VALUES ('Fleece Hoodie Set', 'Zudio', 899, 1399, 'Cozy fleece hoodie with matching joggers. Winter essentials.', '/images/kidswear/winterwear/winterwear1.jpg', (SELECT id FROM categories WHERE name='Boys' AND section='Kids' LIMIT 1), (SELECT id FROM stores WHERE slug='zudio' LIMIT 1), 'Kids', 'Grey', '2-3Y, 4-5Y, 6-7Y, 8-9Y', 4.5, 189, false, true);

-- Admin role grant
UPDATE users SET role = 'ADMIN' WHERE email = '23eg111a28@anurag.edu.in';
